### ISSUE TITLE
Videorecorder issue

### ISSUE THREAD

**Issue by hypertunnelDev** [natmlx/videokit#114] opened 2024-04-22 20:51 UTC
I am getting the following error when trying to run a simple scene with Just a VideoRecorder:

EntryPointNotFoundException: VKTRecorderGetWidth assembly:<unknown assembly> type:<unknown type> member:(null)
VideoKit.MediaRecorder.get_width () (at ./Library/PackageCache/ai.natml.videokit@0.0.18-alpha.7/Runtime/MediaRecorder.cs:116)
VideoKit.Sources.TextureSource..ctor (VideoKit.MediaRecorder recorder, VideoKit.Clocks.IClock clock) (at ./Library/PackageCache/ai.natml.videokit@0.0.18-alpha.7/Runtime/Sources/TextureSource.cs:61)
VideoKit.VideoKitRecorder.CreateVideoInput () (at ./Library/PackageCache/ai.natml.videokit@0.0.18-alpha.7/Runtime/Components/VideoKitRecorder.cs:646)
VideoKit.VideoKitRecorder.StartRecording () (at ./Library/PackageCache/ai.natml.videokit@0.0.18-alpha.7/Runtime/Components/VideoKitRecorder.cs:476)
VideoKit.UI.VideoKitRecordButton.StartRecording () (at ./Library/PackageCache/ai.natml.videokit@0.0.18-alpha.7/Runtime/UI/VideoKitRecordButton.cs:95)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <27124aa0e30a41659b903b822b959bc7>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <cb81df0c49c643b1a04d9fc6ccca2433>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <cb81df0c49c643b1a04d9fc6ccca2433>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <cb81df0c49c643b1a04d9fc6ccca2433>:0)

**Comment by olokobayusuf** [comment] 2024-04-22 20:58
Hey there, this is a duplicate of #111 . We'll be publishing an update that fixes this bug.

**Closed by olokobayusuf** 2024-04-22 20:58 UTC
