### ISSUE TITLE
Editor freezes on shutdown after camera fails to render

### ISSUE THREAD

**Issue by rakkar1974** [natmlx/videokit#22] opened 2023-03-26 17:16 UTC
Editor is freezing when starting multiple times, using VideoKitCameraManager. It always works the first time. Then there is about a 25% chance of freezing when stopping play mode every subsequent run. I know in advance when it will freeze because the camera doesn't initialize.

I thought the problem was domain reload, but after turning off domain reload it still happened.

In the inspector window, I disabled the game object that held VideoKitCameraManager and the editor continued to work. However, with it disabled, I then removed the component in the editor window the the editor froze up.

This happens with the sample from your website

**Comment by rakkar1974** [comment] 2023-03-26 17:48
I tried a similar experiment with the Unity WebCamTexture and the  Windows Camera app. Both of them act similarly at about the same % chance to fail to render on start. However, with those two I am able to stop play mode and stop the app normally, and the camera will work if I try again.

Oddly enough, the same camera has never failed to start rendering when using Google Meet.

**Comment by olokobayusuf** [comment] 2023-03-26 17:52
> I tried a similar experiment with the Unity WebCamTexture and the Windows Camera app. Both of them act similarly at about the same % chance to fail to render on start.

This is good to know. It means the root cause is instability in Windows MediaFoundation.

> However, with those two I am able to stop play mode and stop the app normally, and the camera will work if I try again.

Yup we'll fix this in the upcoming update.

> Oddly enough, the same camera has never failed to start rendering when using Google Meet.

If you're using Google Meet in a browser, then it's likely cos your browser effectively keeps the camera around, even though it isn't streaming. So you're effectively not doing a cold start

**Comment by rakkar1974** [comment] 2023-05-09 12:52
This also occurs with a Logitech BRIO 300

**Comment by olokobayusuf** [comment] 2024-05-30 22:37
This has been fixed in the upcoming VideoKit 0.0.18 update. Feel free to test out the [current alpha builds](https://www.npmjs.com/package/ai.natml.videokit).

**Closed by olokobayusuf** 2024-05-30 22:37 UTC
Labels: bug, critical, windows
