### ISSUE TITLE
Unity Editor freezes or the video never finishes recording after the first run

### ISSUE THREAD

**Issue by degerhandeger** [natmlx/videokit#120] opened 2024-05-07 15:06 UTC
The issue happens on 0.0.18-alpha.8 . Steps to reproduce the issue:
1) Play the Unity Editor for the first time
2) Start a recording
3) Stop the recording
4) View the recorded video
5) Stop the Unity Editor
6) Play the Unity Editor (2nd time)
7) Start a recording
8) Stop recording
9) Unity Editor freezes or No Recorded video from VideoKit.

The editor logs for Unity freezing & not finishing recording cases are attached.

[Unity_Editor_Freezes.log](https://github.com/natmlx/videokit/files/15237448/Unity_Editor_Freezes.log)
[VideoKit_Never_Finishes_Recording.log](https://github.com/natmlx/videokit/files/15237453/VideoKit_Never_Finishes_Recording.log)

**Comment by degerhandeger** [comment] 2024-05-08 09:56
The issue still happen on 0.0.18-alpha.12 . The Unity Editor keeps freezing after the first run in our project. Attached are the logs.

[Editor.log](https://github.com/natmlx/videokit/files/15247112/Editor.log)

**Comment by degerhandeger** [comment] 2024-05-21 15:15
Still happens on 0.0.18-alpha.13 . The Unity Editor keeps freezing after the first run in our project. Attached are the logs.

[Editor.log](https://github.com/natmlx/videokit/files/15391802/Editor.log)

**Comment by degerhandeger** [comment] 2024-05-28 11:59
This issue is not exclusive to Windows. It happens on MacOS as well.

**Comment by olokobayusuf** [comment] 2024-05-28 16:29
@degerhandeger I can't reproduce this on macOS. 
<img width="351" alt="Screenshot 2024-05-28 at 12 29 12 PM" src="https://github.com/natmlx/videokit/assets/17663473/76b972cf-093c-4adf-bc71-d80cc98bdc2f">

Can you share your recorder settings? I want to first reproduce and fix it on macOS before doing the same on Windows.

**Comment by olokobayusuf** [comment] 2024-05-31 13:26
Also cannot reproduce this on Windows with the latest alpha build, alpha 15.

**Comment by degerhandeger** [comment] 2024-05-31 15:59
The Editor continues to freeze on alpha.15 for us. I reproduced the issue by doing the steps mentioned above. Attached are the Editor logs & recorder settings. Also, I don't know whether this would be useful but, removing the Audio mode gave a different error, the Editor did not freeze when it ran for the second time. I also attached this error's screenshot.

[Editor.log](https://github.com/user-attachments/files/15516013/Editor.log)
<img width="352" alt="recorder-settings" src="https://github.com/natmlx/videokit/assets/65905566/ab1aade9-1418-4a3a-b935-cf41fe955ce4">
<img width="785" alt="removing-audio-mode" src="https://github.com/natmlx/videokit/assets/65905566/2f9211d3-9358-43bd-8d53-af6c2d20bbf5">

**Comment by olokobayusuf** [comment] 2024-06-04 16:58
Fixed in VideoKit 0.0.18-alpha.18

**Closed by olokobayusuf** 2024-06-04 16:58 UTC
Labels: bug, critical, windows
