### ISSUE TITLE
Can't upload iOS app because of ai.fxn.fxn3d@0.0.18

### ISSUE THREAD

**Issue by marvpaul** [natmlx/videokit#124] opened 2024-05-30 06:11 UTC
I tried to upload binary to iTunes Connect with VideoKit 0.0.18-alpha15 and it dosen't work because you have a wrongly formatted info.plist for the above mentioned package. 

This bundle is invalid. The value for key CFBundleVersion [0.0.20 (20240520)] in the Info.plist file must be a period-separated list of at most three non-negative integers. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion (ID: 189985f2-d9d3-4cc8-b49e-f5b4ddec5807)

<img width="768" alt="Screenshot 2024-05-30 at 08 10 49" src="https://github.com/natmlx/videokit/assets/10696948/8f6fd19e-8098-4e9d-a2af-1c8483078450">
<img width="1470" alt="Screenshot 2024-05-30 at 08 09 36" src="https://github.com/natmlx/videokit/assets/10696948/dd49fff2-67d1-49ee-8e95-c09ce2c537d2">

**Comment by olokobayusuf** [comment] 2024-05-30 16:06
This was caused by our Function CI system. It has been [fixed upstream](https://github.com/fxnai/fxnc/releases/tag/0.0.21), but we'll be publishing an updated Function Unity version with the fix in a few hours.

**Comment by olokobayusuf** [comment] 2024-05-31 20:52
[Fixed in VideoKit 0.0.18-alpha.16](https://www.npmjs.com/package/ai.natml.videokit)

**Closed by olokobayusuf** 2024-05-31 20:52 UTC
Labels: bug, critical
